### PR TITLE
Change file extension requirement from .txt to .xml #130

### PR DESCRIPTION
**Pull request by zzzzwen**
Ready for review

need to manually delete the original `addressbook.txt` file from local disk to prevent git from uploading it since I have changed .gitignore

Checked actual running of add command, new `addressbook.xml` file generated.
StorageFileTest is working, test data also changed to .xml

---
This change is [Reviewable](https://reviewable.io/reviews/se-edu/addressbook-level2/132)

### CODE REVIEW

**Comment by zzzzwen** [comment]
`expected.txt` and `input.txt` are not changed since I remembered that those are for regression test which only serves in level 1.

I think can remove the `runtests.bat` `runtests.sh` `expected.txt` and `input.txt`  right?

**Comment by damithc** [comment]
@zzzzwen if you look at the level-2 dev guide, you'll see that both type of tests are still used.  
Are the tests passing? You need to run them locally as level 2 does not use gradle.

**Comment by zzzzwen** [comment]
***** actual.txt
|| Enter command: || [Command entered:  add []\[;] p/12345 e/valid@e.mail a/vali
d, address]
|| Names should consist of letters, spaces, numbers, ', - or .
|| ===================================================
***** EXPECTED.TXT
|| Enter command: || [Command entered:  add []\[;] p/12345 e/valid@e.mail a/vali
d, address]
|| Person names should be spaces or alphabetic characters
|| ===================================================
*****

this is one error reported, the other one is .txt to .xml which I have fixed

this one also occurs in the master branch, I'm not sure why

**Comment by pyokagan** [comment]
@zzzzwen 
> this error also occurs in the master branch,

Likely #117 . I provided a (possible) fix there, but don't have time to fully investigate. Maybe you could take over?

**Comment by zzzzwen** [comment]
@damithc My laptop JVM does not have the issues in #117, but for the error I uploaded above, I went to search the `Person names should be spaces or alphabetic characters` in the project package but I cannot find this line in the whole project for both level1 and 2. I'm wondering if the `Messages` has been changed but not updated in the `expected.txt` file

**Comment by zzzzwen** [comment]
@damithc  the commit which changes the message is #118 done by @Neurrone , should I follow this commit to change the `expected.txt` to the correct version?

**Comment by damithc** [comment]
@zzzzwen It's better to report is a bug and create a PR to fix it.

**Comment by zzzzwen** [comment]
ok, except this, anymore changes needed for this pr?

**Comment by zzzzwen** [comment]
After merging with #135 , all tests passing in my computer currently

**Pull request merged**
