### PR TITLE
[35] NullPointerException if viewall is used before list

### LINKED ISSUE #35: NullPointerException if viewall is used before list
The "viewall" command, produces a Null Pointer Exception, even when there is a person at given index. To replicate the issue add a few users and close the program. Then restart and try the first command as viewall 1. However, if we try the list command before viewall the issue disappears. From the code it turns out that viewall works on the last shown list and not the stored file. I am not sure if this was intended or not.

### PR DESCRIPTION
**Pull request by YijinL**
Fixes #35.

### CODE REVIEW

**Comment by damithc** [comment]
1. Update tests?
2. Rename PR to match normal convention

**Comment by damithc** [comment]
Can merge after that.

**Comment by YijinL** [comment]
`runtests.sh` passes.

**Comment by damithc** [comment]
I meant you should add a test to cover this situation.

**Comment by damithc** [comment]
You are also confusing commit message format with PR name format. 
PR name should be a copy paste of issue name with the trailing (not leading) issue number.
In future we can consider making them both the same, but for now they are different.

**Comment by YijinL** [comment]
Oops fixed my other PR names too.
Regression test added in 1ed45b79f8ba48919029686b83aa63a1bcc12603

**Pull request merged**
