### PR TITLE
Remove polymorphic behavior #37

### LINKED ISSUE #37: Remove polymorphic behavior
Polymorphic behavior should be removed as it is not one of the learning outcomes at level 2.
e.g.
execute()
toString()

### PR DESCRIPTION
**Pull request by jia1**
Fixes #37 

Update: Unable to fix tests. Not sure how to proceed.

### CODE REVIEW

**Comment by damithc** [comment]
@jia1 This issue goes deeper than just removing the `@override` annotation. The use of polymorphism itself should be removed.

**Comment by jia1** [comment]
Ready for review

New solution: Remove polymorphic behaviour by removing inheritance. Abstract class is now interface.

**Comment by damithc** [comment]
It's still polymorphic behavior even if you use an interface. If there is some piece of code that can execute a command without caring about what kind of a command it is, then it is using polymorphism. Once you remove polymorphism (and the command pattern), the command execution code should becomes a lot uglier.

**Comment by jia1** [comment]
Prof Damith, thanks for letting me know! Still working on it.

**Comment by damithc** [comment]
@jia1 are you going to resume this? If not, feel free to close for now and reopen when you are ready to resume.

**Comment by damithc** [comment]
Closing for now. Reopen when ready to resume.

**Pull request closed without merging**
