### PR TITLE
README: update Contributors to refer to se-edu #204

### LINKED ISSUE #204: README/Contributors: refer to se-edu instead of listing here
Change the `Contributors` section similar to level1

### PR DESCRIPTION
**Pull request by eugenepeh**
Fix #204

### CODE REVIEW

**Comment by eugenepeh** [comment]
Hello Prof @damithc , 

For your review.
Do remind me of things that you need assist in cleaning up.
Thank you!

**Comment by damithc** [comment]
> Do remind me of things that you need assist in cleaning up.

I think I was mistaken. This is the only issue that needs to be done right now. :-)

**Comment by damithc** [comment]
@Zhiyuan-Amos can merge?

**Comment by Zhiyuan-Amos** [comment]
> can merge?

Yup! (This sounds scary because it seems like a trick question ><). Prof you'll be approving first though right?

**Comment by damithc** [comment]
Yes,  approved. I meant to say 'Could you merge this for me?' :-)

**Comment by Zhiyuan-Amos** [comment]
Haha noted yes prof! :-P

**Pull request merged**
