### PR TITLE
Fix naming standard violation #103

### LINKED ISSUE #103: Fix naming standard violation
`ParserTest:setup()` should be `setUp()`

### PR DESCRIPTION
**Pull request by luyangkenneth**
Fixes #103

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@luyangkenneth submitted v1 for review.

* [v1 1/1] [Fix naming standard violation in ParserTest\#setup\(\) ](https://github.com/se-edu/addressbook-level2/pull/188/commits/dda1629e650475312f02028a951a99cc02e13e5a)

([:books: Archive](https://github.com/se-edu/addressbook-level2/compare/c3c63deb3cb7c4b85ab01b3305e4fc32446279ad...dda1629e650475312f02028a951a99cc02e13e5a))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level2.git refs/pr/188/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by PierceAndy** [comment]
Hi Kenneth, thanks for your contribution.

While this PR tackles a trivial issue, it would still be good to follow [our guidelines on commit messages](https://github.com/oss-generic/process/blob/master/docs/FormatsAndConventions.md#commit-message).

**Comment by luyangkenneth** [comment]
Hi @yamgent and @PierceAndy, thank you for reviewing my PR.

@PierceAndy: May I clarify with you - besides my commit message being too long (52 chars, my bad) - are there any other issues which you'd like me to fix?

**Comment by PierceAndy** [comment]
While the hard limit for commit message titles is 72 characters, it would be best to avoid going past the soft limit of 50 where possible. Some ways of reducing the number of characters is to use the `Scope: change` format as mentioned in the guidelines. 

For instance, `ParserTest: fix naming standard violation` is shorter and easier to read.

**Comment by CanIHasReview** [comment]
# v2

@luyangkenneth submitted v2 for review.

* [v2 1/1] [ParserTest: fix naming standard violation ](https://github.com/se-edu/addressbook-level2/pull/188/commits/272a3ecae14512a08c81ba3520e618af4f0ac751)

([:books: Archive](https://github.com/se-edu/addressbook-level2/compare/c3c63deb3cb7c4b85ab01b3305e4fc32446279ad...272a3ecae14512a08c81ba3520e618af4f0ac751)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level2/compare/ded22293785b7fa29fbb8f58f052810c558f5faf~1...ded22293785b7fa29fbb8f58f052810c558f5faf))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level2.git refs/pr/188/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by luyangkenneth** [comment]
Thanks for the tip @PierceAndy! 🙂

**Pull request merged**
