### PR TITLE
Set up checkstyle #123

### LINKED ISSUE #123: Set up checkstyle
To ensure we do not get any code style violations in master.

Probably should be done after #112  is done.

A PR will also need to resolve all the current errors I get from master: (I copied over the checkstyle config from addressbook-level4)
```
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/Main.java:0: File does not end with a newline. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/Main.java:102: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/commands/IncorrectCommand.java:7:46: '{' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/commands/IncorrectCommand.java:11:51: '{' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/data/person/Address.java:0: File does not end with a newline. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/data/person/Email.java:0: File does not end with a newline. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/data/person/Name.java:16: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/data/person/Name.java:21: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/data/person/ReadOnlyPerson.java:24: Line is longer than 120 characters (found 125). [LineLength]
[ant:checkstyle] [WARN] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/data/tag/UniqueTagList.java:137:23: Name 'TagFoundAndDeleted' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalFinalVariableName]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:0: File does not end with a newline. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:67: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:68: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:70: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:71: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:73: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:74: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:76: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:77: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:79: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:80: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:82: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:83: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:85: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:86: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:88: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:89: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:91: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:92: 'case' child have incorrect indentation level 12, expected level should be 8. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:93: 'block' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/parser/Parser.java:103:44: '{' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/ui/TextUi.java:41:20: '{' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/src/seedu/addressbook/ui/TextUi.java:125:11: 'if' is not followed by whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:49: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:85: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:92: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:115: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:119: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:121: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:123: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:124: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:127: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:132: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:134: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:136: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:137: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:140: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:143: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:145: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:148: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:152: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:154: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:158: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/commands/DeleteCommandTest.java:159: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:49: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:55: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:77: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:91: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:113: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:153: 'array initialization' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:154: 'array initialization' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:187: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:191: 'array initialization' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:192: 'array initialization' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/parser/ParserTest.java:193: 'array initialization' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/util/TestUtil.java:18: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/util/TestUtil.java:22: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/util/TestUtil.java:25: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/util/TestUtil.java:31: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/util/TestUtil.java:35: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [ERROR] /home/pyokagan/pyk/addressbook-level2/test/java/seedu/addressbook/util/TestUtil.java:38: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
```

### PR DESCRIPTION
**Pull request by yamgent**
~~(Note: Work in progress)~~

Fixes #123.

The `checkstyle.xml` is taken from level 4, which had some changes since the creation of issue #123. Hence, this PR also contains the cleanup to fix violations found by checkstyle.

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@yamgent submitted v1 for review.

* [v1 1/4] [Add checkstyle to gradle](https://github.com/se-edu/addressbook-level2/pull/145/commits/8dfc6046ca27cfcde724cb6c2614f7f5f50bb44b)
* [v1 2/4] [Fix coding standard violations in main classes ](https://github.com/se-edu/addressbook-level2/pull/145/commits/898e6f196d8e399f09618f7fa42e931eb41ad834)
* [v1 3/4] [Fix coding standard violations in tests ](https://github.com/se-edu/addressbook-level2/pull/145/commits/f11f2308af0e28adefcd90ea7c31e1b8569bd69b)
* [v1 4/4] [Generate gradle wrapper](https://github.com/se-edu/addressbook-level2/pull/145/commits/5262f2e8fb707e34a01ad83bad2f43655393c8ff)

([:books: Archive](https://github.com/se-edu/addressbook-level2/compare/f92b1d0567e30a36f32d8bd03eae2f3c466fa767...5262f2e8fb707e34a01ad83bad2f43655393c8ff))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level2.git refs/pr/145/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@yamgent did you enable all available rules or only some?

**Comment by yamgent** [comment]
@damithc Yes, all available rules are enabled. As most of the code style issues were fixed in #125, most of the violations that are fixed in this PR are import statement issues, and issues found in new commits after #125.

**Comment by kychua** [comment]
>There were some breaking changes made to checkstyle that causes
>incompatibility with older versions of Gradle. (more info here:
>checkstyle/checkstyle#2107)
>
>At the time of writing, Travis uses Gradle 2.2.1.

Can be phrased more clearly: this means Gradle 2.2.1 is an old version that is incompatible with checkstyle? Here, the last sentence about Gradle 2.2.1 seems unrelated to the previous paragraph.

**Comment by CanIHasReview** [comment]
# v2

@yamgent submitted v2 for review.

* [v2 1/4] [Add checkstyle to gradle](https://github.com/se-edu/addressbook-level2/pull/145/commits/8dfc6046ca27cfcde724cb6c2614f7f5f50bb44b)
* [v2 2/4] [Fix coding standard violations in main classes ](https://github.com/se-edu/addressbook-level2/pull/145/commits/898e6f196d8e399f09618f7fa42e931eb41ad834)
* [v2 3/4] [Fix coding standard violations in tests ](https://github.com/se-edu/addressbook-level2/pull/145/commits/f11f2308af0e28adefcd90ea7c31e1b8569bd69b)
* [v2 4/4] [Generate gradle wrapper](https://github.com/se-edu/addressbook-level2/pull/145/commits/ee4917d6593637185ce991e37b2c4b8224b26d42)

([:books: Archive](https://github.com/se-edu/addressbook-level2/compare/f92b1d0567e30a36f32d8bd03eae2f3c466fa767...ee4917d6593637185ce991e37b2c4b8224b26d42)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level2/commit/ab3e3385ea1b9551ce90c6b2d0eb26af0b804732))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level2.git refs/pr/145/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by yamgent** [comment]
Commit message updated to be more clear about Gradle 2.2.1.

**Comment by damithc** [comment]
@yamgent In next iteration, may be commit messages can be changed to `Fix checkstyle rule violations ...` to be precise?

**Comment by CanIHasReview** [comment]
# v3

@yamgent submitted v3 for review.

* [v3 1/4] [Add checkstyle to gradle](https://github.com/se-edu/addressbook-level2/pull/145/commits/8dfc6046ca27cfcde724cb6c2614f7f5f50bb44b)
* [v3 2/4] [Fix checkstyle rule violations in main classes ](https://github.com/se-edu/addressbook-level2/pull/145/commits/c3482971a870469a3628cd216616af29e125cb0e)
* [v3 3/4] [Fix checkstyle rule violations in tests ](https://github.com/se-edu/addressbook-level2/pull/145/commits/a2b49d0326909723a5a596cb44c013aa585a385a)
* [v3 4/4] [Generate gradle wrapper](https://github.com/se-edu/addressbook-level2/pull/145/commits/86b11a12386e7d171399ba7f32a0749e51b667bf)

([:books: Archive](https://github.com/se-edu/addressbook-level2/compare/f92b1d0567e30a36f32d8bd03eae2f3c466fa767...86b11a12386e7d171399ba7f32a0749e51b667bf)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level2/commit/12bc6626146ec7b00f4143eb0b29945d2560d13d))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level2.git refs/pr/145/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by m133225** [comment]
Just some minor changes to the last commit message.
1. `The gradle wrapper have to be generated` -> `The gradle wrapper has to be generated`
2. `In order to resolve this issue (and to ensure a standard gradle
version used by everyone), generate the wrapper.` -> `Generating the wrapper will help to resolve this issue and ensure a standard gradle version used by everyone.`

**Comment by CanIHasReview** [comment]
# v4

@yamgent submitted v4 for review.

* [v4 1/4] [Add checkstyle to gradle](https://github.com/se-edu/addressbook-level2/pull/145/commits/8dfc6046ca27cfcde724cb6c2614f7f5f50bb44b)
* [v4 2/4] [Fix checkstyle rule violations in main classes ](https://github.com/se-edu/addressbook-level2/pull/145/commits/c3482971a870469a3628cd216616af29e125cb0e)
* [v4 3/4] [Fix checkstyle rule violations in tests ](https://github.com/se-edu/addressbook-level2/pull/145/commits/a2b49d0326909723a5a596cb44c013aa585a385a)
* [v4 4/4] [Generate gradle wrapper](https://github.com/se-edu/addressbook-level2/pull/145/commits/15b17510258c64a12e44e0fc67796696f9b51eeb)

([:books: Archive](https://github.com/se-edu/addressbook-level2/compare/f92b1d0567e30a36f32d8bd03eae2f3c466fa767...15b17510258c64a12e44e0fc67796696f9b51eeb)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level2/commit/4a3e853c5fd666869f1d1fce502a15c964dfa2ed))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level2.git refs/pr/145/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by yamgent** [comment]
@m133225 Thanks for the corrections (I had to modify your correction for 2., because we are told to use imperative-style statements for changes in commit).

**Comment by yamgent** [comment]
@damithc Since the checkstyle.xml is taken from addressbook-level4, should we consider the changes in https://github.com/se-edu/addressbook-level4/pull/279, or should that be in another PR?

**Comment by damithc** [comment]
> @damithc Since the checkstyle.xml is taken from addressbook-level4, should we consider the changes in se-edu/addressbook-level4#279, or should that be in another PR?

Can be a separate PR because this is not a critical flaw. Just create an issue.

**Pull request merged**
