### PR TITLE
Fix typo in header comment #144

### LINKED ISSUE #144: Fix typo in header comment
Header comment in `isValidAddress` in Address class should be 'Returns true if a given string is a valid person *address*.' instead of *email*

### PR DESCRIPTION
**Pull request by limmlingg**
Fixes #144

### CODE REVIEW

**Comment by yamgent** [comment]
Hello @limmlingg, thanks for your PR!

For our repository, we require PR authors to request a review using the CanIHasReview tool. More information is available here: [6. Request a Review](https://github.com/oss-generic/process/blob/master/docs/QuestionsIssuesPrs.md).

**Comment by CanIHasReview** [comment]
# v1

@limmlingg submitted v1 for review.

* [v1 1/1] [Address class: fix typo in header comment ](https://github.com/se-edu/addressbook-level2/pull/186/commits/5a285847ea33ae1cf3c63bbd2e0414009e10a625)

([:books: Archive](https://github.com/se-edu/addressbook-level2/compare/4f5b987767eab233d800ee47712c050d1eb4ff73...5a285847ea33ae1cf3c63bbd2e0414009e10a625))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level2.git refs/pr/186/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by limmlingg** [comment]
Noted. Is it safe to edit the commit message, then force push over the old commit in this case?

**Comment by acjh** [comment]
@limmlingg Yes, you can do that.

**Comment by yamgent** [comment]
@limmlingg For our repository (and only our repository :P), you are allowed to do that, because we have the CanIHasReview tool to keep an archive of our old commits, so we don't lose information even if we overwrite our old commits.

**Comment by CanIHasReview** [comment]
# v2

@limmlingg submitted v2 for review.

* [v2 1/1] [Address class: fix typo in isValidAddress\(String\)'s header comment ](https://github.com/se-edu/addressbook-level2/pull/186/commits/aaa7e21e13dfb4dd2c94175a44d295907515de97)

([:books: Archive](https://github.com/se-edu/addressbook-level2/compare/4f5b987767eab233d800ee47712c050d1eb4ff73...aaa7e21e13dfb4dd2c94175a44d295907515de97)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level2/compare/c92a0512b9bdc41a69d27df2b3fdf6fb510f3ade~1...c92a0512b9bdc41a69d27df2b3fdf6fb510f3ade))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level2.git refs/pr/186/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Pull request merged**
