### PR TITLE
Main#VERSION: Fix typo

### PR DESCRIPTION
**Pull request by 500poundbear**

### CODE REVIEW

**Comment by damithc** [comment]
@Zhiyuan-Amos can you shepherd this PR from a new contributor @500poundbear ?

**Comment by Zhiyuan-Amos** [comment]
Hello @500poundbear! ^^ First, you have to fix travis-CI to ensure that the build passes. Will give you further instructions shortly!

**Comment by damithc** [comment]
@500poundbear the reason Travis is failing is because you haven't updated the tests (i.e. `expected.txt`) to match the change you did to the code.

**Comment by 500poundbear** [comment]
@Zhiyuan-Amos @damithc Sorry about that. Fixed.

**Comment by Zhiyuan-Amos** [comment]
Great job @500poundbear! Now for some finishing touches:

1. Your PR title is slightly long. How about something like `Main#VERSION: Fix typo`?
1. Take a look at https://github.com/oss-generic/process/blob/master/docs/FormatsAndConventions.adoc#commit-organization to find out how to organize your commits. Basically, each commit should not break the build. As such, you will have to perform interactive rebase on your commits to squash them into a single commit. Update the name of the commit to have the same name as your updated PR title.
1. Take a look at https://github.com/oss-generic/process/blob/master/docs/QuestionsIssuesPrs.adoc#326-request-a-review to find out how to request a review.

**Comment by Zhiyuan-Amos** [comment]
@damithc regarding the last commit, it's meant to be there for students to fix right?

**Comment by damithc** [comment]
> @damithc regarding the last commit, it's meant to be there for students to fix right?

Yes, it shouldn't be pushed to this PR anyway @500poundbear One PR should not fix more than one thing.

**Comment by Zhiyuan-Amos** [comment]
> One PR should not fix more than one thing.

@500poundbear what Prof Damith said is right: each PR should focus on fixing 1 issue, with each commit fixing smaller parts of the issue. You can take a look at this PR https://github.com/se-edu/addressbook-level2/pull/141.

As such, fixing the typo in the String and updating the test is considered as 1 PR (it should also be done in the same commit to ensure that Travis-CI doesn't fail i.e. the build doesn't break) because it falls under the same issue of `fixing typo`. However, `updating feedbackToUser to become private` is unrelated to this issue, as such it shouldn't be part of this PR ^^

**Comment by 500poundbear** [comment]
@damithc Thanks for guiding. I committed to the wrong branch and subsequently pushed all branches to master :(

@Zhiyuan-Amos I've rebased and squashed my commits as per your suggestion!

**Comment by Zhiyuan-Amos** [comment]
@500poundbear alright great! One more thing that you need to do (as part of our workflow): Replace github.com in the PR URL with canihasreview.pyokagan.com. The resulting URL should be https://canihasreview.pyokagan.com/se-edu/addressbook-level2/pull/209. Request a review using that web app.

If you want to read up more about our workflow, you can refer to point 3 of https://github.com/se-edu/addressbook-level2/pull/209#issuecomment-326948934

**Comment by Zhiyuan-Amos** [comment]
@500poundbear after discussing with prof, we've decided to simply merge your PR ^^ Thank you for your PR!

Perhaps now you don't understand why we have such a long workflow. It's mainly to ensure that quality code is merged into the code base. You can take a look at one of the PRs that I've done recently: https://github.com/se-edu/addressbook-level4/pull/620, and maybe you'll understand why we're doing all these ^^

**Pull request merged**
